<a href="https://colab.research.google.com/github/IGOR1630/AtividadeIA/blob/main/IA_Ex09_KNN_Pacientes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Treinamento

### Carregando Arquivo de Treinamento (.csv)

In [81]:
import pandas as pd
# Carregando dados do arquivo CSV
url = 'https://raw.githubusercontent.com/IGOR1630/AtividadeIA/main/diabetes.csv'
base_Treinamento = pd.read_csv(url, encoding = 'latin1').values
print("---------------------------------")
print("Dados dos Pacientes - TREINAMENTO")
print("---------------------------------")
print(base_Treinamento)
print("---------------------------------")

# Extração dos Atributos a serem utilizadas pela rede
print("Atributos de Entrada")
print("---------------------------------")
print(base_Treinamento[:, :8])

print("----------------------------")
print("Classificação Supervisionada")
print("----------------------------")
print(base_Treinamento[:, -1])

---------------------------------
Dados dos Pacientes - TREINAMENTO
---------------------------------
[[  6.    148.     72.    ...   0.627  50.      1.   ]
 [  1.     85.     66.    ...   0.351  31.      0.   ]
 [  8.    183.     64.    ...   0.672  32.      1.   ]
 ...
 [  5.    121.     72.    ...   0.245  30.      0.   ]
 [  1.    126.     60.    ...   0.349  47.      1.   ]
 [  1.     93.     70.    ...   0.315  23.      0.   ]]
---------------------------------
Atributos de Entrada
---------------------------------
[[  6.    148.     72.    ...  33.6     0.627  50.   ]
 [  1.     85.     66.    ...  26.6     0.351  31.   ]
 [  8.    183.     64.    ...  23.3     0.672  32.   ]
 ...
 [  5.    121.     72.    ...  26.2     0.245  30.   ]
 [  1.    126.     60.    ...  30.1     0.349  47.   ]
 [  1.     93.     70.    ...  30.4     0.315  23.   ]]
----------------------------
Classificação Supervisionada
----------------------------
[1. 0. 1. 0. 1. 0. 1. 0. 1. 1. 0. 1. 0. 1. 1. 1. 1

### Pré-processamento de Dados

In [82]:
import numpy as np

campos = {
    1: base_Treinamento[:, 0],  # Gravidez
    2: base_Treinamento[:, 1],  # Glicose
    3: base_Treinamento[:, 2],  # PressãoArterial
    4: base_Treinamento[:, 3],  # EspessuraPele
    5: base_Treinamento[:, 4],  # Insulina
    6: base_Treinamento[:, 5],  # IMC
    7: base_Treinamento[:, 6],  # DiabetesPedigreeFunction
    8: base_Treinamento[:, 7],  # Idade
    9: base_Treinamento[:, 8],  # Resultado
}

for chave in range(1, 9):
    campos[chave] = (campos[chave] - min(campos[chave])) / (max(campos[chave]) - min(campos[chave]))

atributos_norm = np.column_stack([campos[chave] for chave in range(1, 9)])
print("--------------------------------")
print("Atributos de Entrada - Numéricos")
print("--------------------------------")
print(atributos_norm)
diagnostico_norm = campos[9]
print("----------------------------------------")
print("Classificação Supervisionada - Numéricos")
print("----------------------------------------")
print(diagnostico_norm)

--------------------------------
Atributos de Entrada - Numéricos
--------------------------------
[[0.35294118 0.74371859 0.59016393 ... 0.50074516 0.23441503 0.48333333]
 [0.05882353 0.42713568 0.54098361 ... 0.39642325 0.11656704 0.16666667]
 [0.47058824 0.91959799 0.52459016 ... 0.34724292 0.25362938 0.18333333]
 ...
 [0.29411765 0.6080402  0.59016393 ... 0.390462   0.07130658 0.15      ]
 [0.05882353 0.63316583 0.49180328 ... 0.4485842  0.11571307 0.43333333]
 [0.05882353 0.46733668 0.57377049 ... 0.45305514 0.10119556 0.03333333]]
----------------------------------------
Classificação Supervisionada - Numéricos
----------------------------------------
[1. 0. 1. 0. 1. 0. 1. 0. 1. 1. 0. 1. 0. 1. 1. 1. 1. 1. 0. 1. 0. 0. 1. 1.
 1. 1. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 1. 1. 0. 0. 0. 1. 0. 1. 0. 0.
 1. 0. 0. 0. 0. 1. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 1. 0. 1. 0. 0. 0. 1. 0.
 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0.
 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1.

### Treinamento do KNN (K-Nearest Neighbor)

In [83]:
from sklearn.neighbors import KNeighborsClassifier
# Treinamento do Knn a partir dos atributos de entrada e classificações com K=3
modelo = KNeighborsClassifier(n_neighbors=11)
modelo.fit(atributos_norm, diagnostico_norm)

# Acurácia do modelo, que é : 1 - (predições erradas / total de predições)
# Acurácia do modelo: indica uma performance geral do modelo.
# Dentre todas as classificações, quantas o modelo classificou corretamente;
# (VP+VN)/N
print('Acurácia: %.3f' % modelo.score(atributos_norm, diagnostico_norm))

Acurácia: 0.784


### ----------------------------------------------------------------------------

# Validação do Aprendizado

### Predição Simples

In [84]:
# for i in range(10, 21):
#  print(f"Test {i}: ", modelo.predict([atributos_norm[i]]))
from random import randint
filhos = randint(0, len(atributos_norm) - 1)
Glicose = randint(0, len(atributos_norm) - 1)
PressaoArterial = randint(0, len(atributos_norm) - 1)
EspessuraPele = randint(0, len(atributos_norm) - 1)
Insulina = randint(0, len(atributos_norm) - 1)
IMC = randint(0, len(atributos_norm) - 1)
DiabetesPedigreeFunction = randint(0, len(atributos_norm) - 1)
Idade = randint(0, len(atributos_norm) - 1)
print("\nPessoa Teste:",
      "\nFilhos:", base_Treinamento[:filhos - 1, :1][-1][0],
      "\nGlicose:", base_Treinamento[:Glicose - 1, :2][-1][1],
      "\nPressãoArterial:", base_Treinamento[:PressaoArterial - 1, :3][-1][2],
      "\nEspessuraPele:", base_Treinamento[:EspessuraPele - 1, :4][-1][3],
      "\nInsulina:", base_Treinamento[:Insulina - 1, :5][-1][4],
      "\nIMC:", base_Treinamento[:IMC - 1, :6][-1][5],
      "\nDiabetesPedigreeFunction:", base_Treinamento[:DiabetesPedigreeFunction - 1, :7][-1][6],
      "\nIdade:", base_Treinamento[:Idade - 1, :8][-1][7],
      )
pessoaTeste = [[atributos_norm[filhos][0]] + [atributos_norm[Glicose][1]] + [atributos_norm[PressaoArterial][2]] + [atributos_norm[EspessuraPele][3]] + [atributos_norm[Insulina][4]] + [atributos_norm[IMC][5]] + [atributos_norm[DiabetesPedigreeFunction][6]] + [atributos_norm[Idade][7]]]
print("\n\nResultado 'Pessoa Teste': ", modelo.predict(pessoaTeste)[0])



Pessoa Teste: 
Filhos: 4.0 
Glicose: 127.0 
PressãoArterial: 76.0 
EspessuraPele: 33.0 
Insulina: 0.0 
IMC: 22.5 
DiabetesPedigreeFunction: 0.727 
Idade: 22.0


Resultado 'Pessoa Teste':  1.0


### Predição a partir de base de dados (.csv)

In [85]:
import pandas as pd
# Carregando dados do arquivo CSV
url = 'https://raw.githubusercontent.com/IGOR1630/AtividadeIA/main/base_treinamento.csv'
base_Testes = pd.read_csv(url, encoding = 'latin1').values
print("----------------------------")
print("Dados dos Pacientes - TESTES")
print("----------------------------")
print(base_Testes)
print("---------------------------------")

# Extração dos Atributos a serem utilizadas pela rede
print("Atributos de Entrada")
print("---------------------------------")
print(base_Testes[:, 1:8])

----------------------------
Dados dos Pacientes - TESTES
----------------------------
[[3.00e+00 1.20e+02 7.00e+01 3.00e+01 0.00e+00 2.75e+01 3.51e-01 2.50e+01
  0.00e+00]
 [2.00e+00 1.35e+02 8.00e+01 2.50e+01 0.00e+00 3.20e+01 2.00e-01 2.20e+01
  1.00e+00]
 [5.00e+00 1.40e+02 8.50e+01 4.00e+01 0.00e+00 3.45e+01 4.10e-01 2.90e+01
  1.00e+00]
 [1.00e+00 9.50e+01 7.00e+01 2.00e+01 8.00e+01 2.65e+01 2.45e-01 2.30e+01
  0.00e+00]
 [4.00e+00 1.10e+02 7.50e+01 3.50e+01 0.00e+00 2.92e+01 3.10e-01 3.10e+01
  1.00e+00]
 [0.00e+00 1.30e+02 6.80e+01 2.80e+01 0.00e+00 2.40e+01 1.98e-01 3.00e+01
  0.00e+00]
 [2.00e+00 1.45e+02 9.00e+01 2.00e+01 9.00e+01 3.10e+01 2.50e-01 2.70e+01
  1.00e+00]
 [6.00e+00 1.50e+02 8.80e+01 3.60e+01 1.20e+02 3.65e+01 5.00e-01 3.50e+01
  1.00e+00]
 [1.00e+00 8.80e+01 6.00e+01 2.20e+01 0.00e+00 2.25e+01 1.25e-01 2.60e+01
  0.00e+00]
 [3.00e+00 1.60e+02 7.70e+01 3.80e+01 0.00e+00 3.50e+01 6.00e-01 4.00e+01
  1.00e+00]]
---------------------------------
Atributos de Entra

### Pré-processamento de Dados

In [86]:
import numpy as np

campos = {
    1: base_Testes[:, 0],  # Gravidez
    2: base_Testes[:, 1],  # Glicose
    3: base_Testes[:, 2],  # PressãoArterial
    4: base_Testes[:, 3],  # EspessuraPele
    5: base_Testes[:, 4],  # Insulina
    6: base_Testes[:, 5],  # IMC
    7: base_Testes[:, 6],  # DiabetesPedigreeFunction
    8: base_Testes[:, 7],  # Idade
    9: base_Testes[:, 8],  # Resultado
}

for chave in range(1, 9):
    campos[chave] = (campos[chave] - min(campos[chave])) / (max(campos[chave]) - min(campos[chave]))

atributos_norm_base_teste = np.column_stack([campos[chave] for chave in range(1, 9)])
print("--------------------------------")
print("Atributos de Entrada - Numéricos")
print("--------------------------------")
print(atributos_norm_base_teste)
diagnostico_norm_base_teste = campos[9]
print("----------------------------------------")
print("Classificação Supervisionada - Numéricos")
print("----------------------------------------")
print(diagnostico_norm_base_teste)

--------------------------------
Atributos de Entrada - Numéricos
--------------------------------
[[0.5        0.44444444 0.33333333 0.5        0.         0.35714286
  0.47578947 0.16666667]
 [0.33333333 0.65277778 0.66666667 0.25       0.         0.67857143
  0.15789474 0.        ]
 [0.83333333 0.72222222 0.83333333 1.         0.         0.85714286
  0.6        0.38888889]
 [0.16666667 0.09722222 0.33333333 0.         0.66666667 0.28571429
  0.25263158 0.05555556]
 [0.66666667 0.30555556 0.5        0.75       0.         0.47857143
  0.38947368 0.5       ]
 [0.         0.58333333 0.26666667 0.4        0.         0.10714286
  0.15368421 0.44444444]
 [0.33333333 0.79166667 1.         0.         0.75       0.60714286
  0.26315789 0.27777778]
 [1.         0.86111111 0.93333333 0.8        1.         1.
  0.78947368 0.72222222]
 [0.16666667 0.         0.         0.1        0.         0.
  0.         0.22222222]
 [0.5        1.         0.56666667 0.9        0.         0.89285714
  1.        

### Predição da Base

In [87]:
base_Predicao = modelo.predict((atributos_norm_base_teste))
print("Classificações: ", base_Predicao)

Classificações:  [0. 0. 1. 0. 1. 0. 1. 1. 0. 1.]


### Imprimindo a predição

In [88]:
for i, d in enumerate(base_Predicao):
  print(f'Instância {i + 1}', 'possui diabetes.' if d == 1.0 else 'não possui diabetes.')

Instância 1 não possui diabetes.
Instância 2 não possui diabetes.
Instância 3 possui diabetes.
Instância 4 não possui diabetes.
Instância 5 possui diabetes.
Instância 6 não possui diabetes.
Instância 7 possui diabetes.
Instância 8 possui diabetes.
Instância 9 não possui diabetes.
Instância 10 possui diabetes.
